### PR TITLE
273 graylog running twice

### PR DESCRIPTION
**Pull request by evalott100**
Solved by changing the port for logging to graylog.

### CODE REVIEW

**Comment by evalott100** [comment]
More on this:

This is the graylog input for the artemis port we were using:
image

This is the one for the normal gelf which doesn't double send logs:
image

**Review by DominicOram — CHANGES_REQUESTED** [review]
Good spot but I think we need to dig a bit more:
* I want a separate input for Artemis, it makes it easier to filter and to throttle just Artemis if required
* If we don't know why it happened it could just start happening again

Additionally, there's a lot of code changes here that seem unrelated to the graylog stuff, can we remove them?

**Comment by evalott100** [comment]
> I want a separate input for Artemis, it makes it easier to filter and to throttle just Artemis if required
This would make sense, my plan would be to change the config of the artemis port so those two other parameters match the default gelf one. If the artemis port is in use during then this would cause problems, so it'd  need to be during shutdown.

> If we don't know why it happened it could just start happening again
I pretty much agree. If changing those parameters doesn't work then we'll know that it is some unique issue with the port that isn't being shown to us. At that point I'll find a sysadmin and get  them to investigate.

> there's a lot of code changes here that seem unrelated to the graylog stuff, can we remove them? 
Yea I think I accidentally added them. I'll recommit without the port change since we want to get our original port working anyway.

**Comment by evalott100** [comment]
Changing the Artemis config on graylog didn't work. I'll need to ask scicomp about this.

**Comment by DominicOram** [comment]
> Changing the Artemis config on graylog didn't work. I'll need to ask scicomp about this.

Thanks, we should think of a good way to track when we're waiting on something else. Could you add a new column to the project board for `Blocked`, put the issue in it then add a comment on to the original issue about what we're waiting for

**Comment by DominicOram** [comment]
This PR also contains completely unrelated code changes, can we remove them please?

**Comment by evalott100** [comment]
This was caused by the setting "Remove matches from 'All messages' stream" in the steam not being selected. Now it is graylog is only logging once.

**Pull request closed without merging**
