### PR TITLE
572 deploy dodal as repo in prod fixed

### LINKED ISSUE #572: Deploy dodal as a repo in prod
Currently we deploy artemis as a repo but not dodal, this is annoying if we have to make live fixes to both.

## Acceptance Criteria
* Deploy structure is changed to include separate folders e.g. `artemis_v.../artemis` and `artemis_v..../dodal`
* Deploy script updated
* Restart Artemis in GDA updated

### PR DESCRIPTION
**Pull request by olliesilvester**
Fixes #572  and #627

### To test:
1. Run "deploy_artemis.py dev" and confirm issue requirements are satifsfied, and that the symlink is correct
2. Confirm beamline deployment location is correct

### CODE REVIEW

**Review by dperl-dls — CHANGES_REQUESTED** [review]
If I try to run either
`python deploy/deploy_artemis.py dev` or `./deploy/deploy_artemis.sh dev` I get a:
`PermissionError: [Errno 13] Permission denied: './dls_dev_env.sh'`
In a freshly cloned repo from this branch. I think it's probably because it writes to /tmp/ and the system policy here is to not allow execution from /tmp/
I feel that the bash script should have a --help option, and either script should ideally let you specify the location

**Comment by olliesilvester** [comment]
> If I try to run either `python deploy/deploy_artemis.py dev` or `./deploy/deploy_artemis.sh dev` I get a: `PermissionError: [Errno 13] Permission denied: './dls_dev_env.sh'` In a freshly cloned repo from this branch. I think it's probably because it writes to /tmp/ and the system policy here is to not allow execution from /tmp/

Are you able to run deploy_artemis.py dev from the main branch? That script also runs ./dls_dev_env.sh from /tmp/

**Comment by dperl-dls** [comment]
Yeah, can't run that one either. so I guess it is technically a separate issue that this doesn't work on rhel8 but we might as well fix it

**Comment by olliesilvester** [comment]
It works on my Red Hat 8 machine, but I can look into what's causing the permission error

**Comment by dperl-dls** [comment]
oh, interesting. I wonder if I just need to get someone to change the security policy for my machine then.

**Review by dperl-dls — APPROVED** [review]
On discussion, we will ignor potential security policy interference in execution from /tmp/ since that doesn't affect many people. will revisit if it becomes a bigger problem

**Pull request merged**
