### PR TITLE
314: Added basic deploy script

### LINKED ISSUE #314: Formalise and document releases and deployments
Now that Artemis is getting close to being in production we should improve and document:
* Release processes (including release notes)
* Deployment processes

These processes should aim to be as automated as possible

### PR DESCRIPTION
**Pull request by DominicOram**
Fixes #314

### To test:
1. Follow instructions at https://github.com/DiamondLightSource/python-artemis/wiki/Creating-a-release-and-deploying-it#deploying-a-release to test a release locally
2. Confirm a full deployment happens as expected

### CODE REVIEW

**Review by dperl-dls — COMMENTED** [review]
Must: add git to dependencies

**Comment by dperl-dls** [comment]
Running `deploy_artemis.py` gives me the following error:

```
Gathering version tags from this repo
Traceback (most recent call last):
  File "/home/ziq44869/Downloads/python-artemis-0.9.13/deploy_artemis.py", line 36, in <module>
    this_repo = Repo(os.path.join(os.path.dirname(__file__), ".git"))
  File "/home/ziq44869/Downloads/python-artemis-0.9.13/.venv/lib/python3.10/site-packages/git/repo/base.py", line 194, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/ziq44869/Downloads/python-artemis-0.9.13/.git
```

**Review by dperl-dls — COMMENTED** [review]
Nit: it'd be nice to have one script that does everything - set up the venv, activate it, and deploy

**Review by dperl-dls — CHANGES_REQUESTED** [review]
Running `deploy_artemis.py` gives me the following error:

```
Gathering version tags from this repo
Traceback (most recent call last):
  File "/home/ziq44869/Downloads/python-artemis-0.9.13/deploy_artemis.py", line 36, in <module>
    this_repo = Repo(os.path.join(os.path.dirname(__file__), ".git"))
  File "/home/ziq44869/Downloads/python-artemis-0.9.13/.venv/lib/python3.10/site-packages/git/repo/base.py", line 194, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/ziq44869/Downloads/python-artemis-0.9.13/.git
```

**Comment by DominicOram** [comment]
Updated docs at https://github.com/DiamondLightSource/python-artemis/wiki/Creating-a-release-and-deploying-it#deploying-a-release to be a bit clearer

**Review by noemifrisina — APPROVED** [review]
Looks good to me.

**Pull request merged**
