### PR TITLE
Use artemis-specific zocalo environment

### PR DESCRIPTION
**Pull request by rjgildea**
This avoids bluesky logs ending up in the Zocalo/data analysis graylog stream.

See also https://github.com/DiamondLightSource/python-artemis/issues/27

Add E501 to flake ignore: Since we are already relying on black to apply an appropriate max line length, and flake8 can sometimes disagree ignore this particular warning

### CODE REVIEW

**Review by DominicOram — CHANGES_REQUESTED** [review]
Thank you, would you be able to fix the tests? I like having the check in both as we may well have contributions from people that are not regularly using `black`. I haven't seen them disagree as long as you have them set up with the same line lengths?

**Comment by rjgildea** [comment]
> I like having the check in both as we may well have contributions from people that are not regularly using `black`. I haven't seen them disagree as long as you have them set up with the same line lengths?

Without ignoring E501 set, flake8 complained about the line lengths that I changed in https://github.com/DiamondLightSource/python-artemis/pull/203/commits/4bae73dfb8b96f217b9ebf65135b1e40d83dca88.  It also complained about [this line](https://github.com/DiamondLightSource/python-artemis/blob/4bae73dfb8b96f217b9ebf65135b1e40d83dca88/src/artemis/zocalo_interaction.py#L94) which black does not touch.

**Comment by rjgildea** [comment]
> > I like having the check in both as we may well have contributions from people that are not regularly using `black`. I haven't seen them disagree as long as you have them set up with the same line lengths?
> 
> Without ignoring E501 set, flake8 complained about the line lengths that I changed in [4bae73d](https://github.com/DiamondLightSource/python-artemis/commit/4bae73dfb8b96f217b9ebf65135b1e40d83dca88). It also complained about [this line](https://github.com/DiamondLightSource/python-artemis/blob/4bae73dfb8b96f217b9ebf65135b1e40d83dca88/src/artemis/zocalo_interaction.py#L94) which black does not touch.

By way of standalone example:
```
$ cat long_lines.py 
a_really_long_string = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"


def function_with_really_long_docstring():
    """This doesn't really tell you anything but it is reaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaally long"""
    pass
$ black long_lines.py 
All done! ✨ 🍰 ✨
1 file left unchanged.
[hko55533@ws175 rjgildea]$ flake8 long_lines.py 
long_lines.py:1:80: E501 line too long (130 > 79 characters)
long_lines.py:5:80: E501 line too long (123 > 79 characters)
```

In my experience it is best to leave anything to do with formatting (such as line length) to black, since that makes any necessary changes automatically, and disable related checks in flake8 (since as demonstrated above, they are not necessarily consistent with black). I don't understand under what circumstances people would be running flake8 but not black.

**Review by DominicOram — APPROVED** [review]
We've had previous issues where people were running w/o the pre-commit hooks and so not using `black`/`flake8` and issues crept in. I think with https://github.com/DiamondLightSource/python-artemis/pull/172 and https://github.com/DiamondLightSource/python-artemis/pull/205 this is less likely to happen though so happy to blanket ignore E501

**Review by abbiemery — APPROVED** [review]

**Pull request merged**
