### PR TITLE
399 random order tests

### LINKED ISSUE #399: Randomise tests
https://github.com/DiamondLightSource/python-artemis/issues/393 was missed because the tests had issues where they shared state between them. If we randomise the tests this should hopefully be less likely to happen.

## Acceptance Criteria
* Tests run in CI are in a random order
* This random order is reproducible and it is documented how to reproduce it (e.g. if tests fail in a particular order I can run this order locally)

### PR DESCRIPTION
**Pull request by dperl-dls**
Fixes #399 
Randomises the order in which tests are run, including in CI, in order to help identify any interdependent tests.

Tests will fail currently; they are fixed in #405, which is merged into main now

### To test:
0. You might need to `pip install pytest-random-order` (or run `./dls_dev_env.sh` again)
1. Run `pytest --random-order -m "not s03` 
2. Observe that some ispyb tests fail sometimes
3. Merge main
4. Rerun tests a few times and see they always pass

### CODE REVIEW

**Comment by dperl-dls** [comment]
@evalott100 Can you review this please?

**Comment by evalott100** [comment]
* I get "no module dlstbx" when tests are ran. 
* The nexgen is out of date and will throw errors without an upgrade (version >= should be specified in setup.cfg).

**Comment by dperl-dls** [comment]
Hopefully these issues should be fixed now:
- removed nexgen version tag since the release is out
- moved symbolic link creation later in the dls_de_env script once the folder for it to go in actually exists (:man_facepalming:)

**Comment by dperl-dls** [comment]
closed because I messed up a merge and it was easier to recreate in #443

**Pull request closed without merging**
