### PR TITLE
204: Added script to set up dev environment

### LINKED ISSUE #204: Script to set up dev environment
Setting the dev environment up should be as easy as possible, currently theres a few steps. We should reduce them into once script.

### PR DESCRIPTION
**Pull request by DominicOram**
Fixes #204 

To test:
* Run the script and confirm it reinstalls your environment and passes

### CODE REVIEW

**Comment by rjgildea** [comment]
Thanks for adding this - it should make it easier for newcomers to get started. However, when I run the script it gets as far as running the tests before complaining about missing `mockito` module:
```
$ sh dls_dev_env.sh 

    Loading a conda environment for Python 3.10
    If there are any problems, please contact dataanalysis@diamond.ac.uk

    Need a 3rd party Python package installing? First, consider using the
    user-based install option of pip to test it. (I.e., use
    $ pip install --user ... For further details, see $ pip help install)

    This will install the package in ~/.local
    If a site-wide installation is required, contact Scientific Software.
    For further details, see $ pip help install

Already loaded!
Creating a virtualenv for this project...
Pipfile: /dls/science/users/hko55533/software/python-artemis/Pipfile
Using /dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/bin/python3.1 (3.10.4) to create virtualenv...
⠧ Creating virtual environment...created virtual environment CPython3.10.4.final.0-64 in 8160ms
  creator CPython3Posix(dest=/dls/science/users/hko55533/software/python-artemis/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/hko55533/.local/share/virtualenv)
    added seed packages: pip==22.1.2, setuptools==63.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /dls/science/users/hko55533/software/python-artemis/.venv
Installing dependencies from Pipfile.lock (a72d9e)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 72/72 — 00:01:18
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
pre-commit installed at .git/hooks/pre-commit
=================================================================================================== test session starts ====================================================================================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /dls/science/users/hko55533/software/python-artemis, configfile: pyproject.toml, testpaths: src
plugins: cov-3.0.0
collected 32 items / 8 errors / 7 deselected / 25 selected                                                                                                                                                                 

========================================================================================================== ERRORS ==========================================================================================================
__________________________________________________________________________ ERROR collecting src/artemis/devices/unit_tests/test_beam_converter.py __________________________________________________________________________
ImportError while importing test module '/dls/science/users/hko55533/software/python-artemis/src/artemis/devices/unit_tests/test_beam_converter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/artemis/devices/unit_tests/test_beam_converter.py:2: in <module>
    from mockito import when
E   ModuleNotFoundError: No module named 'mockito'
______________________________________________________________________________ ERROR collecting src/artemis/devices/unit_tests/test_eiger.py _______________________________________________________________________________
ImportError while importing test module '/dls/science/users/hko55533/software/python-artemis/src/artemis/devices/unit_tests/test_eiger.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/dls_sw/apps/python/miniforge/4.10.0-0/envs/python3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/artemis/devices/unit_tests/test_eiger.py:2: in <module>
    from mockito import ANY, mock, verify, when
E   ModuleNotFoundError: No module named 'mockito'
...
```
Output of `pipenv run pip list`:
```
$ pipenv run pip list
Package                Version               Editable project location
---------------------- --------------------- -------------------------------------------------------
aniso8601              9.0.1
apischema              0.17.5
attrs                  22.1.0
bidict                 0.22.0
bluesky                1.8.3
certifi                2022.6.15
charset-normalizer     2.1.0
click                  8.1.3
coverage               6.4.2
cycler                 0.11.0
dataclasses-json       0.5.7
docopt                 0.6.2
event-model            1.17.2
Flask                  2.1.3
Flask-RESTful          0.3.9
freephil               0.2.1
graypy                 2.1.0
greenlet               2.0.0a2
h5py                   3.7.0
hdf5plugin             3.3.1
HeapDict               1.0.1
historydict            1.2.3
idna                   3.3
importlib-resources    5.9.0
iniconfig              1.1.1
ispyb                  6.11.0
itsdangerous           2.1.2
Jinja2                 3.1.2
jsonschema             4.9.0
MarkupSafe             2.1.1
marshmallow            3.17.0
marshmallow-enum       1.5.1
msgpack                1.0.4
msgpack-numpy          0.4.8
mypy-extensions        0.4.3
mysql-connector-python 8.0.30
networkx               2.8.5
nexgen                 0.6.9
numpy                  1.23.1
ophyd                  1.6.4.post76+g0895f9f
packaging              21.3
pika                   1.3.0
Pint                   0.19.2
pip                    22.1.2
pluggy                 1.0.0
protobuf               3.20.1
py                     1.11.0
pydantic               1.9.1
pyepics                3.5.1
pyparsing              3.0.9
pyrsistent             0.18.1
pytest                 7.1.2
pytest-cov             3.0.0
python-artemis         0.0.0                 /dls/science/users/hko55533/software/python-artemis/src
pytz                   2022.1
PyYAML                 6.0
requests               2.28.1
scanspec               0.5.4
setuptools             63.1.0
six                    1.16.0
SQLAlchemy             1.4.39
stomp.py               8.0.1
super-state-machine    2.0.2
tabulate               0.8.10
tomli                  2.0.1
toolz                  0.12.0
tqdm                   4.64.0
typing_extensions      4.3.0
typing-inspect         0.7.1
urllib3                1.26.11
Werkzeug               2.2.1
wheel                  0.37.1
workflows              2.24.1
zict                   2.2.0
zocalo                 0.22.0
```

**Review by bentom08 — DISMISSED** [review]
Looks like this worked fine however a couple of points:

1.  I got  `OperationalError: disk I/O error` when running the pre-commit hooks. Not sure how impactful this is on the functionality of the script
2.  Permissions for the script need changing, currently the permissions are -rw-rw-r--.  The owner needs execute permissions at a minimum.

**Comment by DominicOram** [comment]
@rjgildea That looks like you may have been running with the `Pipfile` that got corrupted when you tried `pipenv install --dev .` before. Are you definitely on this branch cleanly?
@bentom08 I cant reproduce that 1st point, what does `.git/hooks/pre-commit` look like? Does it exist and what permissions does it have?

**Comment by bentom08** [comment]
I think the 1st point may have been an issue on my end. After clearing up some space in my home directory I don't have this issue any more.

**Comment by DominicOram** [comment]
@evalott100 can you merge this if you're happy it worked on your machine?

**Pull request merged**
